In [3]:
import polars as pl
from pl_compare import compare

is het beter om de data direct in te laden (polars kan dat) of eerst omzetten in een file?
>> volgens dagster kan je het beste meteen inladen in de database (als files niet veel te groot zijn)
>> kijk naar: Direct Loading with I/O Managers: https://docs.dagster.io/guides/build/io-managers

todo:
    
done:
    name.basics
    title.basics
    title.principals
    title.crew (split and add directors and writers from title.principals and remove duplicates)

## transform title.basics

In [2]:
test = pl.read_csv(
    "/media/user/Data/dirkv/Code/dagster/dagster-workspace/data/imdb/inputs/imdb_files/title.basics.tsv.gz",
    has_header=True,
    separator="\t",
    truncate_ragged_lines=True,
    null_values="\\N",
    quote_char=None,
    schema={
        "tconst": pl.Utf8,
        "titleType": pl.Utf8,
        "primaryTitle": pl.Utf8,
        "originalTitle": pl.Utf8,
        "isAdult": pl.Int64,
        "startYear": pl.Int64,
        "endYear": pl.Int64,
        "runtimeMinutes": pl.Int64,
        "genres": pl.Utf8,
    }
)
title_basics = test.drop("genres") # de 0 bij is adult zou al goed geladen moeten worden door postgresl
genres = test.select(
    pl.col("tconst"), 
    pl.col("genres").str.split(",")
    ).explode("genres")

# transforming name.basics

In [8]:
test = pl.read_csv(
    "/media/user/Data/dirkv/Code/dagster/dagster-workspace/data/imdb/inputs/imdb_files/name.basics.tsv.gz",
    has_header=True,
    separator="\t",
    truncate_ragged_lines=True,
    null_values="\\N",
    quote_char=None,
    schema={
        "nconst": pl.Utf8,
        "primaryName": pl.Utf8,
        "birthYear": pl.Int16,
        "deathYear": pl.Int16,
        "primaryProfession": pl.Utf8,
        "knownForTitles": pl.Utf8,
        
    }
)
# primary_profession = test.select(
#     pl.col("nconst"),
#     pl.col("primaryProfession").str.split(",")
# ).explode("primaryProfession")

# known_for_titles = test.select(
#     pl.col("nconst"),
#     pl.col("knownForTitles").str.split(",")
# ).explode("knownForTitles")
name_basics = test.drop(["primaryProfession", "knownForTitles"])

In [9]:
name_basics

shape: (15_175_268, 4)
┌───────────┬────────────────────┬───────────┬───────────┐
│ nconst    ┆ primaryName        ┆ birthYear ┆ deathYear │
│ ---       ┆ ---                ┆ ---       ┆ ---       │
│ str       ┆ str                ┆ i16       ┆ i16       │
╞═══════════╪════════════════════╪═══════════╪═══════════╡
│ nm0000001 ┆ Fred Astaire       ┆ 1899      ┆ 1987      │
│ nm0000002 ┆ Lauren Bacall      ┆ 1924      ┆ 2014      │
│ nm0000003 ┆ Brigitte Bardot    ┆ 1934      ┆ 2025      │
│ nm0000004 ┆ John Belushi       ┆ 1949      ┆ 1982      │
│ nm0000005 ┆ Ingmar Bergman     ┆ 1918      ┆ 2007      │
│ …         ┆ …                  ┆ …         ┆ …         │
│ nm9993714 ┆ Romeo del Rosario  ┆ null      ┆ null      │
│ nm9993716 ┆ Essias Loberg      ┆ null      ┆ null      │
│ nm9993717 ┆ Harikrishnan Rajan ┆ null      ┆ null      │
│ nm9993718 ┆ Aayush Nair        ┆ null      ┆ null      │
│ nm9993719 ┆ Andre Hill         ┆ null      ┆ null      │
└───────────┴────────────────────┴───────────┴───────────┘

# transforming title.principals

In [3]:
test = pl.read_csv(
    "/media/user/Data/dirkv/Code/dagster/dagster-workspace/data/imdb/inputs/imdb_files/title.principals.tsv.gz",
    has_header=True,
    separator="\t",
    truncate_ragged_lines=True,
    null_values="\\N",
    quote_char=None,
    schema={
        "tconst": pl.Utf8,
        "ordering": pl.Int16,
        "nconst": pl.Utf8,
        "category": pl.Utf8,
        "job": pl.Utf8,
        "characters": pl.Utf8
    }
)
title_principals = test.with_columns(
    pl.col("characters").str.replace_all(r'[\[\]"]', "")
)
# we leave job for wat it is
title_principals

shape: (98_486_993, 6)
┌───────────┬──────────┬───────────┬─────────────────┬─────────────────────────┬────────────┐
│ tconst    ┆ ordering ┆ nconst    ┆ category        ┆ job                     ┆ characters │
│ ---       ┆ ---      ┆ ---       ┆ ---             ┆ ---                     ┆ ---        │
│ str       ┆ i16      ┆ str       ┆ str             ┆ str                     ┆ str        │
╞═══════════╪══════════╪═══════════╪═════════════════╪═════════════════════════╪════════════╡
│ tt0000001 ┆ 1        ┆ nm1588970 ┆ self            ┆ null                    ┆ Self       │
│ tt0000001 ┆ 2        ┆ nm0005690 ┆ director        ┆ null                    ┆ null       │
│ tt0000001 ┆ 3        ┆ nm0005690 ┆ producer        ┆ producer                ┆ null       │
│ tt0000001 ┆ 4        ┆ nm0374658 ┆ cinematographer ┆ director of photography ┆ null       │
│ tt0000002 ┆ 1        ┆ nm0721526 ┆ director        ┆ null                    ┆ null       │
│ …         ┆ …        ┆ …         ┆ …               ┆ …                       ┆ …          │
│ tt9916880 ┆ 17       ┆ nm0996406 ┆ director        ┆ principal director      ┆ null       │
│ tt9916880 ┆ 18       ┆ nm1482639 ┆ writer          ┆ null                    ┆ null       │
│ tt9916880 ┆ 19       ┆ nm2586970 ┆ writer          ┆ books                   ┆ null       │
│ tt9916880 ┆ 20       ┆ nm1594058 ┆ producer        ┆ producer                ┆ null       │
│ tt9916880 ┆ 21       ┆ nm1482639 ┆ producer        ┆ producer                ┆ null       │
└───────────┴──────────┴───────────┴─────────────────┴─────────────────────────┴────────────┘

In [ ]:
title_principals.partition_by("ordering")

## transforming title.crew

In [2]:
test = pl.read_csv(
    "/media/user/Data/dirkv/Code/dagster/dagster-workspace/data/imdb/inputs/imdb_files/title.crew.tsv.gz",
    has_header=True,
    separator="\t",
    truncate_ragged_lines=True,
    null_values="\\N",
    quote_char=None,
    schema={
        "tconst": pl.Utf8,
        "directors": pl.Utf8,
        "writers": pl.Utf8,
    }
)

directors = test.select(
    pl.col("tconst"),
    pl.col("directors").str.split(","),
).explode("directors")
writers = test.select(
    pl.col("tconst"),
    pl.col("writers").str.split(","),
).explode("writers")

In [3]:
directors

shape: (14_708_270, 2)
┌───────────┬────────────┐
│ tconst    ┆ directors  │
│ ---       ┆ ---        │
│ str       ┆ str        │
╞═══════════╪════════════╡
│ tt0000001 ┆ nm0005690  │
│ tt0000002 ┆ nm0721526  │
│ tt0000003 ┆ nm0721526  │
│ tt0000004 ┆ nm0721526  │
│ tt0000005 ┆ nm0005690  │
│ …         ┆ …          │
│ tt9916848 ┆ nm1485677  │
│ tt9916850 ┆ nm1485677  │
│ tt9916852 ┆ nm1485677  │
│ tt9916856 ┆ nm10538645 │
│ tt9916880 ┆ nm0996406  │
└───────────┴────────────┘

## transforming title.ratings (is al goed, alleen rekening houden met \N)

In [3]:
title_ratings = pl.read_csv(
    "/media/user/Data/dirkv/Code/dagster/dagster-workspace/data/imdb/inputs/imdb_files/title.ratings.tsv.gz",
    has_header=True,
    separator="\t",
    truncate_ragged_lines=True,
    null_values="\\N",
    quote_char=None,
    schema={
        "tconst": pl.Utf8,
        "averageRating": pl.Float16,
        "numVotes": pl.UInt32,
    }
)

title_ratings

shape: (1_650_038, 3)
┌───────────┬───────────────┬──────────┐
│ tconst    ┆ averageRating ┆ numVotes │
│ ---       ┆ ---           ┆ ---      │
│ str       ┆ f16           ┆ u32      │
╞═══════════╪═══════════════╪══════════╡
│ tt0000001 ┆ 5.699219      ┆ 2200     │
│ tt0000002 ┆ 5.5           ┆ 311      │
│ tt0000003 ┆ 6.3984375     ┆ 2308     │
│ tt0000004 ┆ 5.1015625     ┆ 196      │
│ tt0000005 ┆ 6.199219      ┆ 3037     │
│ …         ┆ …             ┆ …        │
│ tt9916846 ┆ 5.300781      ┆ 7        │
│ tt9916848 ┆ 5.199219      ┆ 7        │
│ tt9916850 ┆ 6.0           ┆ 7        │
│ tt9916852 ┆ 5.699219      ┆ 7        │
│ tt9916880 ┆ 7.699219      ┆ 10       │
└───────────┴───────────────┴──────────┘

## title.episode  (is al goed, alleen rekening houden met \N)

In [21]:
test = pl.read_csv(
    "/media/user/Data/dirkv/Code/dagster/dagster-workspace/data/imdb/inputs/imdb_files/title.episode.tsv.gz",
    has_header=True,
    separator="\t",
    truncate_ragged_lines=True,
    null_values="\\N",
    quote_char=None,
    schema={
        "tconst": pl.Utf8,
        "parentTconst": pl.Utf8,
        "seasonNumber": pl.UInt16,
        "episodeNumber": pl.UInt32,
    }
)
test

shape: (9_550_705, 4)
┌───────────┬──────────────┬──────────────┬───────────────┐
│ tconst    ┆ parentTconst ┆ seasonNumber ┆ episodeNumber │
│ ---       ┆ ---          ┆ ---          ┆ ---           │
│ str       ┆ str          ┆ u16          ┆ u32           │
╞═══════════╪══════════════╪══════════════╪═══════════════╡
│ tt0031458 ┆ tt32857063   ┆ null         ┆ null          │
│ tt0041951 ┆ tt0041038    ┆ 1            ┆ 9             │
│ tt0042816 ┆ tt0989125    ┆ 1            ┆ 17            │
│ tt0042889 ┆ tt0989125    ┆ null         ┆ null          │
│ tt0043426 ┆ tt0040051    ┆ 3            ┆ 42            │
│ …         ┆ …            ┆ …            ┆ …             │
│ tt9916846 ┆ tt1289683    ┆ 3            ┆ 18            │
│ tt9916848 ┆ tt1289683    ┆ 3            ┆ 17            │
│ tt9916850 ┆ tt1289683    ┆ 3            ┆ 19            │
│ tt9916852 ┆ tt1289683    ┆ 3            ┆ 20            │
│ tt9916880 ┆ tt0985991    ┆ 4            ┆ 2             │
└───────────┴──────────────┴──────────────┴───────────────┘

## title.akas (is al goed, alleen rekening houden met \N en een boolean)

In [ ]:
title_akas = pl.read_csv(
    "/media/user/Data/dirkv/Code/dagster/dagster-workspace/data/imdb/inputs/imdb_files/title.akas.tsv.gz",
    has_header=True,
    separator="\t",
    truncate_ragged_lines=True,
    null_values="\\N",
    quote_char=None,
    schema={
        "titleId": pl.Utf8,
        "ordering": pl.UInt16,
        "title": pl.Utf8,
        "region": pl.Utf8,
        "language": pl.Utf8,
        "types": pl.Utf8,
        "attributes": pl.Utf8,
        "isOriginalTitle": pl.UInt8
    }
)
title_akas = title_akas.with_columns(
        pl.col("isOriginalTitle").cast(pl.Boolean)
    )

ColumnNotFoundError: unable to find column "isAdult"; valid columns: ["titleId", "ordering", "title", "region", "language", "types", "attributes", "isOriginalTitle"]

# kijken of title ratings en titlebasics op elkaar zijn afgestemd

In [25]:
# title_basics.select(
#     pl.col("tconst")
# ).equals(
#     title_ratings.select(
#         pl.col("tconst")
#     )
# )

len(set(title_principals["tconst"]) - set(title_basics["tconst"])) # wat zit in 1e, maar niet in 2e

1816

In [26]:
len(set(title_basics["tconst"]) - set(title_principals["tconst"])) # wat zit in 1e, maar niet in 2e

1181351

In [28]:
set(title_basics["tconst"]) - set(title_principals["tconst"])

{'tt9800348',
 'tt6795662',
 'tt16067678',
 'tt31795391',
 'tt2344119',
 'tt15885712',
 'tt21987146',
 'tt13624372',
 'tt1012401',
 'tt12677626',
 'tt33366230',
 'tt35235652',
 'tt7469836',
 'tt39293201',
 'tt9343670',
 'tt15637982',
 'tt5392096',
 'tt28308445',
 'tt7740882',
 'tt6482262',
 'tt37231547',
 'tt2231448',
 'tt9805200',
 'tt30280951',
 'tt33339076',
 'tt3064108',
 'tt2671902',
 'tt15974646',
 'tt13457254',
 'tt37592744',
 'tt1052230',
 'tt11992096',
 'tt37561072',
 'tt12662136',
 'tt7328562',
 'tt38128298',
 'tt9716046',
 'tt35108065',
 'tt15826788',
 'tt6928736',
 'tt12193894',
 'tt35483706',
 'tt39380246',
 'tt8752648',
 'tt33377777',
 'tt9897220',
 'tt15056772',
 'tt39163564',
 'tt15946210',
 'tt33466071',
 'tt11986484',
 'tt4087736',
 'tt21616652',
 'tt19309582',
 'tt21393900',
 'tt3626682',
 'tt38516794',
 'tt35613590',
 'tt32160034',
 'tt32568855',
 'tt19115000',
 'tt31418728',
 'tt8255336',
 'tt7853080',
 'tt14831904',
 'tt7528622',
 'tt15800624',
 'tt2264628',
 'tt39862246',
 'tt15860404',
 'tt3412238',
 'tt4489326',
 'tt35538876',
 'tt3193810',
 'tt6662434',
 'tt0239390',
 'tt14128682',
 'tt19224092',
 'tt11475682',
 'tt6652562',
 'tt36887337',
 'tt16073110',
 'tt3160806',
 'tt6726268',
 'tt4989024',
 'tt38799673',
 'tt37536014',
 'tt16095810',
 'tt37109688',
 'tt15889206',
 'tt38118055',
 'tt28108856',
 'tt5403478',
 'tt15132630',
 'tt9265652',
 'tt15638364',
 'tt4576524',
 'tt18283562',
 'tt11575976',
 'tt2702766',
 'tt3496808',
 'tt16068372',
 'tt14231924',
 'tt12537792',
 'tt1030215',
 'tt13753564',
 'tt32982636',
 'tt2346388',
 'tt12816752',
 'tt35032702',
 'tt28583784',
 'tt5405608',
 'tt6891424',
 'tt2272090',
 'tt9302472',
 'tt14490088',
 'tt3265250',
 'tt14994724',
 'tt15934206',
 'tt12831250',
 'tt31151262',
 'tt3284834',
 'tt37282426',
 'tt14575688',
 'tt27211822',
 'tt21865694',
 'tt19704568',
 'tt11831276',
 'tt4063134',
 'tt7030386',
 'tt21900138',
 'tt39221577',
 'tt28294633',
 'tt6947202',
 'tt2889630',
 'tt34289893',
 'tt37996838',
 'tt15902616',
 'tt4197906',
 'tt10100828',
 'tt2149078',
 'tt38129762',
 'tt39333787',
 'tt32417138',
 'tt31868365',
 'tt14716898',
 'tt1667026',
 'tt5257650',
 'tt32500819',
 'tt9640626',
 'tt15956572',
 'tt35792785',
 'tt5064496',
 'tt36116553',
 'tt27672391',
 'tt28615098',
 'tt18290920',
 'tt3835576',
 'tt3875324',
 'tt32315301',
 'tt33072170',
 'tt15954868',
 'tt36614769',
 'tt34294525',
 'tt35860439',
 'tt4231180',
 'tt5684382',
 'tt37642100',
 'tt8131942',
 'tt1792349',
 'tt3930168',
 'tt0239412',
 'tt27349391',
 'tt4953992',
 'tt15954974',
 'tt3050824',
 'tt11800588',
 'tt5010646',
 'tt16460164',
 'tt4135212',
 'tt5408306',
 'tt5411284',
 'tt22473746',
 'tt37245801',
 'tt4059546',
 'tt10990202',
 'tt0335605',
 'tt6989608',
 'tt22051860',
 'tt15954684',
 'tt3057142',
 'tt12234172',
 'tt3889250',
 'tt39066522',
 'tt10471806',
 'tt5755226',
 'tt5833124',
 'tt5064902',
 'tt15890414',
 'tt19044248',
 'tt8028496',
 'tt6867174',
 'tt38721057',
 'tt6424048',
 'tt37407802',
 'tt11088640',
 'tt1793262',
 'tt3886352',
 'tt12367620',
 'tt15603842',
 'tt14390590',
 'tt9434022',
 'tt21900848',
 'tt3946252',
 'tt5141416',
 'tt40254935',
 'tt1792392',
 'tt2681370',
 'tt30057820',
 'tt12004906',
 'tt35674450',
 'tt16116702',
 'tt4090654',
 'tt36435043',
 'tt4597480',
 'tt7734280',
 'tt12952524',
 'tt16100294',
 'tt3014142',
 'tt29925355',
 'tt6335448',
 'tt13346432',
 'tt27451287',
 'tt14199386',
 'tt5131108',
 'tt38589586',
 'tt4443124',
 'tt38129815',
 'tt4947778',
 'tt36599174',
 'tt33059612',
 'tt15995584',
 'tt3965030',
 'tt35763852',
 'tt15840758',
 'tt14362876',
 'tt27451308',
 'tt15928930',
 'tt31960838',
 'tt14722956',
 'tt38408920',
 'tt27818853',
 'tt27111165',
 'tt25643706',
 'tt19394928',
 'tt1085210',
 'tt15641732',
 'tt30630946',
 'tt3049776',
 'tt2817940',
 'tt28366117',
 'tt8215550',
 'tt32103652',
 'tt7795652',
 'tt27988862',
 'tt27331182',
 'tt16995018',
 'tt12599690',
 'tt21368034',
 'tt7068736',
 'tt21446268',
 'tt18309222',
 'tt14101608',
 'tt35546584',
 'tt3024066',
 'tt37956027',
 'tt6861428',
 'tt7842784',
 'tt11481576',
 'tt19401050',
 'tt33549010',
 'tt4864712',
 'tt15643382',
 'tt6190770',
 'tt35233034',
 'tt40070314',
 'tt15849298',
 'tt7946782',
 'tt22090308',
 'tt3956516',
 'tt14781420',
 'tt1948525',
 'tt1024717',
 'tt38780120',
 'tt4008674',
 'tt2014174',
 'tt27756024',
 'tt10669920',
 'tt39368377',
 'tt1030773',
 'tt10116718',
 'tt12944998',
 'tt16155092',
 'tt31037533',
 'tt12382880',
 'tt35286821',
 'tt13350160',
 'tt6249536',
 'tt12798248',
 'tt31842775',
 'tt32514652',
 'tt30782722',
 'tt16456524',
 'tt4266028',
 'tt36592771',
 'tt23142502',
 'tt14864346',
 'tt14701974',
 'tt38822004',
 'tt26737067',
 'tt8406542',
 'tt12826318',
 'tt27169872',
 'tt39635403',
 'tt4466982',
 'tt2860082',
 'tt1112718',
 'tt16065676',
 'tt27127927',
 'tt37645571',
 'tt31528751',
 'tt37803934',
 'tt1987071',
 'tt6568616',
 'tt15861694',
 'tt31723415',
 'tt3033642',
 'tt3393540',
 'tt27643988',
 'tt0997639',
 'tt28358990',
 'tt2242001',
 'tt38206615',
 'tt22866708',
 'tt7597980',
 'tt6978010',
 'tt16492488',
 'tt15577846',
 'tt7564126',
 'tt2745232',
 'tt6935182',
 'tt3125354',
 'tt28546732',
 'tt2233493',
 'tt21895704',
 'tt1744290',
 'tt15880794',
 'tt40793001',
 'tt34990943',
 'tt16493058',
 'tt5895604',
 'tt16069168',
 'tt0374022',
 'tt6496336',
 'tt33373965',
 'tt16099160',
 'tt34525341',
 'tt40346910',
 'tt37276248',
 'tt35682363',
 'tt38390419',
 'tt38887599',
 'tt13477570',
 'tt28480713',
 'tt35851670',
 'tt14221764',
 'tt35919415',
 'tt2837736',
 'tt40044478',
 'tt10275794',
 'tt12211624',
 'tt32813756',
 'tt1084572',
 'tt19759506',
 'tt2178669',
 'tt15634216',
 'tt1854627',
 'tt28806474',
 'tt15997498',
 'tt40416410',
 'tt13528094',
 'tt13499072',
 'tt40197391',
 'tt31615288',
 'tt15865040',
 'tt27369347',
 'tt32542078',
 'tt17004566',
 'tt17491814',
 'tt11833752',
 'tt15955148',
 'tt15971754',
 'tt4867670',
 'tt13921088',
 'tt3355132',
 'tt3939668',
 'tt9823338',
 'tt37107008',
 'tt22394606',
 'tt8184158',
 'tt12826258',
 'tt6360416',
 'tt2968300',
 'tt21994374',
 'tt37069265',
 'tt39338106',
 'tt14508026',
 'tt4732426',
 'tt3937474',
 'tt21236726',
 'tt29793669',
 'tt10457334',
 'tt2314352',
 'tt27730560',
 'tt15583584',
 'tt31036724',
 'tt1583509',
 'tt8098784',
 'tt15595630',
 'tt18334986',
 'tt31216688',
 'tt8780150',
 'tt15629436',
 'tt16341652',
 'tt2683732',
 'tt5797818',
 'tt15546732',
 'tt15296748',
 'tt18382340',
 'tt16092428',
 'tt20899418',
 'tt0819676',
 'tt4446672',
 'tt4821274',
 'tt2867634',
 'tt12445112',
 'tt31270143',
 'tt20897914',
 'tt16097688',
 'tt6624912',
 'tt15980372',
 'tt2221222',
 'tt5071162',
 'tt32450458',
 'tt32515203',
 'tt16094496',
 'tt8211040',
 'tt32740484',
 'tt6036330',
 'tt3535870',
 'tt8282206',
 'tt35888820',
 'tt37527894',
 'tt4898702',
 'tt15497616',
 'tt14168552',
 'tt8249612',
 'tt7464746',
 'tt32258590',
 'tt5497396',
 'tt10485406',
 'tt36752962',
 'tt30701232',
 'tt31968309',
 'tt5808016',
 'tt13484666',
 'tt37791835',
 'tt0410709',
 'tt31150996',
 'tt15631848',
 'tt23330436',
 'tt40645741',
 'tt4891406',
 'tt0949672',
 'tt13574584',
 'tt16299770',
 'tt1069184',
 'tt33164612',
 'tt2181121',
 'tt16065470',
 'tt1030797',
 'tt33531588',
 'tt12311804',
 'tt35766870',
 'tt15897986',
 'tt39378074',
 'tt11786286',
 'tt19666810',
 'tt3933486',
 'tt21421460',
 'tt15795878',
 'tt4539034',
 'tt12960898',
 'tt34891967',
 'tt3933184',
 'tt39213220',
 'tt21894448',
 'tt12483828',
 'tt39075280',
 'tt16974970',
 'tt15190188',
 'tt7567860',
 'tt4824732',
 'tt3941612',
 'tt8142338',
 'tt7506948',
 'tt6409474',
 'tt14329760',
 'tt15635108',
 'tt15946294',
 'tt15647220',
 'tt2339234',
 'tt24670808',
 'tt33092138',
 'tt2698778',
 'tt36777271',
 'tt15936114',
 'tt36759255',
 'tt35893649',
 'tt8849256',
 'tt33009057',
 'tt17691072',
 'tt13477786',
 'tt21226532',
 'tt11423624',
 'tt16099486',
 'tt12399136',
 'tt35270057',
 'tt26449179',
 'tt13647158',
 'tt27655171',
 'tt0130473',
 'tt15602882',
 'tt8027110',
 'tt7310100',
 'tt13131692',
 'tt1006647',
 'tt16459686',
 'tt32206345',
 'tt27679617',
 'tt15951730',
 'tt15629352',
 'tt4920736',
 'tt36616426',
 'tt7879232',
 'tt12093572',
 'tt22168534',
 'tt3931802',
 'tt5406028',
 'tt4838844',
 'tt7878914',
 'tt2278593',
 'tt39312532',
 'tt39072191',
 'tt25401436',
 'tt32493983',
 'tt31531693',
 'tt0235328',
 'tt3925616',
 'tt9408160',
 'tt28228500',
 'tt12458818',
 'tt28135909',
 'tt3196930',
 'tt38357946',
 'tt16318736',
 'tt39306493',
 'tt6588848',
 'tt28806353',
 'tt35931468',
 'tt39742496',
 'tt27773427',
 'tt14765292',
 'tt6016102',
 'tt23396318',
 'tt14431316',
 'tt15862812',
 'tt15338428',
 'tt1959024',
 'tt1364822',
 'tt4988656',
 'tt6516456',
 'tt10971154',
 'tt1071337',
 'tt15814694',
 'tt9279798',
 'tt3847278',
 'tt32552764',
 'tt15814164',
 'tt1109846',
 'tt4617792',
 'tt3916132',
 'tt19638358',
 'tt15817378',
 'tt12701376',
 'tt2867806',
 'tt32596854',
 'tt15580258',
 'tt11160434',
 'tt3940592',
 'tt36763973',
 'tt34381527',
 'tt35257873',
 'tt1012395',
 'tt15645216',
 'tt1031051',
 'tt15750696',
 'tt14801036',
 'tt2270577',
 'tt14755076',
 'tt10505608',
 'tt10528454',
 'tt19045044',
 'tt16025058',
 'tt13198108',
 'tt36543854',
 'tt39622800',
 'tt18989682',
 'tt15063342',
 'tt14592754',
 'tt12038462',
 'tt36466726',
 'tt4482162',
 'tt7857522',
 'tt5209686',
 'tt11363964',
 'tt26773178',
 'tt1450468',
 'tt8151464',
 'tt30460787',
 'tt35680350',
 'tt2346390',
 'tt4905126',
 'tt15275770',
 'tt15813780',
 'tt38941338',
 'tt32367130',
 'tt12012926',
 'tt4688732',
 'tt31589385',
 'tt30422216',
 'tt12392998',
 'tt31869410',
 'tt10896560',
 'tt5205668',
 'tt3825550',
 'tt5853232',
 'tt9054152',
 'tt2244209',
 'tt14099266',
 'tt10318020',
 'tt35303423',
 'tt8066870',
 'tt1077427',
 'tt4989466',
 'tt38964019',
 'tt37778283',
 'tt2149621',
 'tt20899284',
 'tt31940598',
 'tt17719328',
 'tt15955592',
 'tt10488988',
 'tt14444382',
 'tt37834799',
 'tt15704162',
 'tt1649532',
 'tt13680746',
 'tt12279816',
 'tt35284883',
 'tt14951418',
 'tt27050841',
 'tt38907061',
 'tt27646850',
 'tt15490470',
 'tt31025144',
 'tt34608331',
 'tt6159046',
 'tt8858312',
 'tt11927758',
 'tt0991826',
 'tt39733684',
 'tt3494532',
 'tt3934250',
 'tt4822152',
 'tt39289749',
 'tt4128734',
 'tt16230858',
 'tt15627914',
 'tt14547734',
 'tt4247026',
 'tt27637134',
 'tt39164495',
 'tt6990310',
 'tt5387560',
 'tt21321904',
 'tt1738608',
 'tt37957672',
 'tt11722054',
 'tt39294536',
 'tt27044195',
 'tt5599172',
 'tt22015202',
 'tt2687562',
 'tt2131638',
 'tt35913566',
 'tt4951278',
 'tt33085668',
 'tt9095096',
 'tt3601000',
 'tt5408854',
 'tt19759670',
 'tt1301165',
 'tt17050116',
 'tt31150688',
 'tt8270720',
 'tt26316459',
 'tt3956420',
 'tt31498745',
 'tt4988510',
 'tt36728719',
 'tt31615193',
 'tt36551909',
 'tt4274334',
 'tt2983344',
 'tt38821892',
 'tt36130520',
 'tt31452417',
 'tt39392391',
 'tt40673019',
 'tt6041588',
 'tt37730357',
 'tt39467314',
 'tt17375484',
 'tt32874569',
 'tt37285117',
 'tt6844270',
 'tt22778580',
 'tt2762164',
 'tt27115620',
 'tt23143428',
 'tt32588811',
 'tt14655468',
 'tt25546754',
 'tt40256364',
 'tt3224986',
 'tt10020506',
 'tt4442932',
 'tt2726320',
 'tt4922078',
 'tt40602550',
 'tt37485712',
 'tt16069594',
 'tt13786364',
 'tt3903524',
 'tt9693986',
 'tt9373250',
 'tt7457016',
 'tt6276098',
 'tt1862129',
 'tt4317276',
 'tt34992963',
 'tt15886136',
 'tt4987298',
 'tt31796153',
 'tt15923862',
 'tt36999586',
 'tt15593302',
 'tt15937160',
 'tt29486655',
 'tt29732424',
 'tt13315888',
 'tt9037206',
 'tt15955718',
 'tt5415368',
 'tt15796458',
 'tt39247469',
 'tt35677546',
 'tt34366890',
 'tt3670976',
 'tt2455750',
 'tt21394122',
 'tt3812486',
 'tt5393272',
 'tt7473688',
 'tt4248594',
 'tt7234774',
 'tt11366850',
 'tt14876584',
 'tt15814632',
 'tt31034124',
 'tt14860456',
 'tt3922366',
 'tt4605238',
 'tt13628904',
 'tt9015762',
 'tt13854802',
 'tt16071394',
 'tt36436220',
 'tt2152974',
 'tt9363088',
 'tt35826733',
 'tt37232226',
 'tt37256906',
 'tt3999642',
 'tt1895727',
 'tt34966402',
 'tt2824216',
 'tt8338286',
 'tt5393598',
 'tt1909942',
 'tt10563416',
 'tt8614060',
 'tt14844764',
 'tt14423960',
 'tt8010070',
 'tt28939682',
 'tt40041282',
 'tt18073376',
 'tt4880770',
 'tt16460492',
 'tt30826281',
 'tt15677420',
 'tt29606654',
 'tt14577946',
 'tt18116732',
 'tt19858332',
 'tt5085982',
 'tt1546476',
 'tt12929130',
 'tt10034032',
 'tt8891078',
 'tt38821083',
 'tt6560272',
 'tt16456660',
 'tt5410740',
 'tt33336506',
 'tt5448992',
 'tt1645343',
 'tt5813262',
 'tt8857286',
 'tt15167382',
 'tt24022390',
 'tt34862726',
 'tt34545760',
 'tt40062455',
 'tt14839080',
 'tt15267608',
 'tt9315356',
 'tt15925422',
 'tt2528850',
 'tt10468222',
 'tt2680264',
 'tt19845692',
 'tt3927790',
 'tt4844060',
 'tt5512596',
 'tt37740827',
 'tt9108176',
 'tt10937064',
 'tt37898054',
 'tt39309964',
 'tt31531070',
 'tt21889338',
 'tt13451456',
 'tt38131591',
 'tt4220948',
 'tt38991026',
 'tt14521496',
 'tt14574634',
 'tt20563564',
 'tt34388963',
 'tt5396020',
 'tt3933196',
 'tt1459845',
 'tt37273724',
 'tt25407344',
 'tt1762287',
 'tt22434456',
 'tt36120696',
 'tt5063414',
 'tt27542700',
 'tt6322272',
 'tt15796348',
 'tt4672440',
 'tt37060403',
 'tt2333864',
 'tt16975002',
 'tt15926696',
 'tt7729006',
 'tt5169272',
 'tt8761574',
 'tt15588914',
 'tt15900050',
 'tt35855588',
 'tt34152275',
 'tt0970627',
 'tt14633726',
 'tt8800708',
 'tt1100628',
 'tt35270312',
 'tt40611196',
 'tt4988064',
 'tt15825344',
 'tt1914271',
 'tt38822620',
 'tt4953366',
 'tt38132224',
 'tt10111588',
 'tt3265978',
 'tt10204186',
 'tt3970748',
 'tt2690682',
 'tt14939296',
 'tt7643436',
 'tt31025268',
 'tt15304268',
 'tt39922040',
 'tt15995148',
 'tt17496720',
 'tt29232338',
 'tt28383882',
 'tt27428160',
 'tt16458644',
 'tt5409580',
 'tt5098404',
 'tt6685460',
 'tt5389198',
 'tt31722642',
 'tt8169316',
 'tt21898274',
 'tt32019388',
 'tt12380168',
 'tt32880317',
 'tt4154872',
 'tt1812456',
 'tt35081541',
 'tt33396521',
 'tt21097030',
 'tt38629082',
 'tt27880226',
 'tt12646234',
 'tt8258710',
 'tt33366721',
 'tt36731556',
 'tt4198126',
 'tt12034672',
 'tt6477020',
 'tt37958618',
 'tt15972700',
 'tt6581014',
 'tt7741350',
 'tt13717742',
 'tt15628098',
 'tt4870338',
 'tt30819629',
 'tt35828378',
 'tt18276786',
 'tt10880326',
 'tt5874222',
 'tt32421053',
 'tt37365680',
 'tt37893387',
 'tt29596293',
 'tt7544450',
 'tt37238209',
 'tt16415300',
 'tt29402527',
 'tt10937656',
 'tt35921877',
 'tt32116193',
 'tt15084382',
 'tt11080248',
 'tt8119830',
 'tt2817968',
 'tt5392112',
 'tt10870250',
 'tt5841394',
 'tt21313032',
 'tt4784158',
 'tt33058847',
 'tt40413049',
 'tt15025056',
 'tt36589506',
 'tt28590247',
 'tt4212252',
 'tt12106994',
 'tt7913970',
 'tt6563238',
 'tt9153620',
 ...}

In [17]:
title_basics.head()

shape: (5, 8)
┌───────────┬───────────┬──────────────┬─────────────┬─────────┬───────────┬─────────┬─────────────┐
│ tconst    ┆ titleType ┆ primaryTitle ┆ originalTit ┆ isAdult ┆ startYear ┆ endYear ┆ runtimeMinu │
│ ---       ┆ ---       ┆ ---          ┆ le          ┆ ---     ┆ ---       ┆ ---     ┆ tes         │
│ str       ┆ str       ┆ str          ┆ ---         ┆ i64     ┆ i64       ┆ i64     ┆ ---         │
│           ┆           ┆              ┆ str         ┆         ┆           ┆         ┆ i64         │
╞═══════════╪═══════════╪══════════════╪═════════════╪═════════╪═══════════╪═════════╪═════════════╡
│ tt0000001 ┆ short     ┆ Carmencita   ┆ Carmencita  ┆ 0       ┆ 1894      ┆ null    ┆ 1           │
│ tt0000002 ┆ short     ┆ Le clown et  ┆ Le clown et ┆ 0       ┆ 1892      ┆ null    ┆ 5           │
│           ┆           ┆ ses chiens   ┆ ses chiens  ┆         ┆           ┆         ┆             │
│ tt0000003 ┆ short     ┆ Poor Pierrot ┆ Pauvre      ┆ 0       ┆ 1892      ┆ null    ┆ 5           │
│           ┆           ┆              ┆ Pierrot     ┆         ┆           ┆         ┆             │
│ tt0000004 ┆ short     ┆ Un bon bock  ┆ Un bon bock ┆ 0       ┆ 1892      ┆ null    ┆ 12          │
│ tt0000005 ┆ short     ┆ Blacksmith   ┆ Blacksmith  ┆ 0       ┆ 1893      ┆ null    ┆ 1           │
│           ┆           ┆ Scene        ┆ Scene       ┆         ┆           ┆         ┆             │
└───────────┴───────────┴──────────────┴─────────────┴─────────┴───────────┴─────────┴─────────────┘

In [18]:
title_principals.head()

shape: (5, 6)
┌───────────┬──────────┬───────────┬─────────────────┬─────────────────────────┬────────────┐
│ tconst    ┆ ordering ┆ nconst    ┆ category        ┆ job                     ┆ characters │
│ ---       ┆ ---      ┆ ---       ┆ ---             ┆ ---                     ┆ ---        │
│ str       ┆ i64      ┆ str       ┆ str             ┆ str                     ┆ str        │
╞═══════════╪══════════╪═══════════╪═════════════════╪═════════════════════════╪════════════╡
│ tt0000001 ┆ 1        ┆ nm1588970 ┆ self            ┆ null                    ┆ Self       │
│ tt0000001 ┆ 2        ┆ nm0005690 ┆ director        ┆ null                    ┆ null       │
│ tt0000001 ┆ 3        ┆ nm0005690 ┆ producer        ┆ producer                ┆ null       │
│ tt0000001 ┆ 4        ┆ nm0374658 ┆ cinematographer ┆ director of photography ┆ null       │
│ tt0000002 ┆ 1        ┆ nm0721526 ┆ director        ┆ null                    ┆ null       │
└───────────┴──────────┴───────────┴─────────────────┴─────────────────────────┴────────────┘

In [32]:
title_basics.select(
    pl.col("runtimeMinutes").max(),
    pl.col("tconst")
    )

shape: (12_373_014, 2)
┌────────────────┬───────────┐
│ runtimeMinutes ┆ tconst    │
│ ---            ┆ ---       │
│ i64            ┆ str       │
╞════════════════╪═══════════╡
│ 3692080        ┆ tt0000001 │
│ 3692080        ┆ tt0000002 │
│ 3692080        ┆ tt0000003 │
│ 3692080        ┆ tt0000004 │
│ 3692080        ┆ tt0000005 │
│ …              ┆ …         │
│ 3692080        ┆ tt9916848 │
│ 3692080        ┆ tt9916850 │
│ 3692080        ┆ tt9916852 │
│ 3692080        ┆ tt9916856 │
│ 3692080        ┆ tt9916880 │
└────────────────┴───────────┘